name: floral
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - ipykernel
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - pip
  - python<3.11
  - pytorch-cuda=11.8
  - seaborn=0.13.2
  - torchinfo
  # - typing-extensions=4.5.0  # resolves an annoying compatibility issue with tensorflow-federated
  - pip:
    - torchvision
    - flwr[simulation]<=1.8
    - flwr_datasets[vision]
    - hydra-core
    - hydra-optuna-sweeper
    - hydra-submitit-launcher
    # - hydra-joblib-launcher
    # - hydra-ray-launcher
    # - py-spy  # for profiling clients (see scripts/test.py header)
    # Comment out next 2 lines if running experiments without tff datasets
    - tensorflow
    - tensorflow-federated=0.87.0

# Run the following if you want to get the right build of torchvision:
# >> pip install --upgrade torchvision
