---
num_rounds: 500
batch_size: 64
lr: 0.001
router_lr: 0.1  #${eval_num:'3.0 * ${lr}'}
# lora_lr: 0.003  #${eval_num:'0.1 * ${lr}'}

global_optimizer:
  _target_: torch.optim.Adam
  lr: 0.001

dataset:
  dataset: cifar100
  subtask: none
  num_clients: 100
  num_clusters: 10
  num_classes: 100
  image_key: img
  label_key: fine_label
  batch_size: ${batch_size}
  test_batch_size: ${test_batch_size}
  dataloader_cfg: ${dataloader}
  val_proportion: ${val_proportion}
  train_reduction: 0.0

loss_fn:
  _target_: torch.nn.CrossEntropyLoss

model:
  _target_: floral.model.VGG8
  batch_norm: False

trainer:
  # clip_grad_norm: 100.0
  batch_keys:
    - ${dataset.image_key}
    - ${dataset.label_key}

strategy:
  fraction_fit: 0.5
  fraction_evaluate: 0.5
