---
num_rounds: 300  # about 90 min per 100 rounds of floral_rank4
batch_size: 32
lr: 0.1
router_lr: 0.1

floral:
  num_clusters: 10
  use_normlora: True
ensemble:
  num_clusters: 10

dataset:
  dataset: emnist
  data_dir: ${data_dir}
  statistics_dir: dataset_statistics
  client_list: default  # any str that is not an actual filename would work
  batch_size: ${batch_size}
  test_batch_size: ${test_batch_size}
  validation_mode: ${validation_mode}

loss_fn:
  _target_: torch.nn.CrossEntropyLoss

model:
  _target_: floral.model.EmnistResNetGN

strategy:
  fraction_fit: 0.02  # about 22 clients
  fraction_evaluate: 0.02  # about 22 clients

