---
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
submitit_folder: ${hydra.sweep.dir}/.submitit/%j
name: ${experiment}

# These should be overridden per task
timeout_min: 720
cpus_per_task: 8
mem_gb: 8
gpus_per_node: null

# Cluster specific
partition: cscc-cpu-p
qos: cscc-cpu-qos

# Default args
tasks_per_node: 1
nodes: 1
array_parallelism: 256
additional_parameters: {}
comment: null
constraint: null
exclude: null
cpus_per_gpu: null
gpus_per_task: null
mem_per_gpu: null
mem_per_cpu: null
account: null
signal_delay_s: 120
max_num_timeout: 0
setup: null
srun_args: null
